# Site settings
title: the whatleads.to blog
email: team@whatleads.to
description: > # this means to ignore newlines until "baseurl:"
  Updates, ideas, and general musings from the whatleads.to team.
baseurl: "/whatleadsto-blog" # the subpath of your site, e.g. /blog/
url: "http://localhost:4000" # the base hostname & protocol for your site
twitter_username: whatleadsto
github_username:  whatleadsto

# Build settings
markdown: kramdown
